/*****************************************************************************************************************
NAME:    3.4 Adventure Works—Create Answers
PURPOSE: Create 8 SQL queries to answer the questions generated by my class and other sources

MODIFICATION LOG:
Ver      Date        Author           Description
-----   ----------   --------------   ------------------------------------------------------------------------------
1.0     09/23/2026   Omarji Joaquim      1. Built this script for EC IT143


RUNTIME: 
2s

NOTES: 
This script contains SQL queries answering eight business and metadata questions 
from the AdventureWorks database. It was built to practice translating user questions 
into SQL statements, focusing on clarity, proper formatting, and documentation. 
The queries cover marginal, moderate, and increased complexity business scenarios, 
as well as metadata exploration using INFORMATION_SCHEMA views.
 
******************************************************************************************************************/
-- Q1: What is the list price of the product named "Mountain-100 Silver, 44"? (Author: Omarji)
-- A1: This query retrieves the list price for the specified product from the Production.Product table.
SELECT ListPrice
FROM Production.Product
WHERE Name = 'Mountain-100 Silver, 44';

-- Q2: Which product category has the highest number of products listed in the Product table? (Author: Omarji)
-- A2: This query counts products by category and returns the category with the highest count.
SELECT TOP 1 pc.Name AS CategoryName, COUNT(*) AS ProductCount
FROM Production.Product p
JOIN Production.ProductSubcategory ps ON p.ProductSubcategoryID = ps.ProductSubcategoryID
JOIN Production.ProductCategory pc ON ps.ProductCategoryID = pc.ProductCategoryID
GROUP BY pc.Name
ORDER BY ProductCount DESC;

-- Q3: Which sales territories generated the highest sales revenue, and how many orders did each territory receive? (Author: Alexander Agyei-Mintah)
-- A3: This query calculates total revenue and order count per territory.
SELECT st.Name AS Territory, SUM(soh.TotalDue) AS TotalRevenue, COUNT(soh.SalesOrderID) AS OrderCount
FROM Sales.SalesOrderHeader soh
JOIN Sales.SalesTerritory st ON soh.TerritoryID = st.TerritoryID
GROUP BY st.Name
ORDER BY TotalRevenue DESC;

-- Q4: Which customers have placed the most orders, and what is the total value of their purchases? (Author: Alexander Agyei-Mintah)
-- A4: This query counts orders per customer and sums their total purchase value.
SELECT c.CustomerID, COUNT(soh.SalesOrderID) AS OrdersPlaced, SUM(soh.TotalDue) AS TotalValue
FROM Sales.SalesOrderHeader soh
JOIN Sales.Customer c ON soh.CustomerID = c.CustomerID
GROUP BY c.CustomerID
ORDER BY OrdersPlaced DESC;

-- Q5: I want to understand how our road bikes sold in 2013. Can you break it down by month and by color, showing how many units sold and how much money we made? I'm hoping to spot patterns by season. (Author: Mmbone Christine)
-- A5: This query analyzes road bike sales in 2013, grouped by month and product color. It shows units sold and total revenue, helping identify seasonal patterns.

SELECT MONTH(soh.OrderDate) AS OrderMonth,
       p.Color,
       SUM(sod.OrderQty) AS UnitsSold,
       SUM(sod.LineTotal) AS TotalRevenue
FROM Sales.SalesOrderHeader soh
JOIN Sales.SalesOrderDetail sod ON soh.SalesOrderID = sod.SalesOrderID
JOIN Production.Product p ON sod.ProductID = p.ProductID
JOIN Production.ProductSubcategory ps ON p.ProductSubcategoryID = ps.ProductSubcategoryID
WHERE ps.Name = 'Road Bikes'
  AND YEAR(soh.OrderDate) = 2013
GROUP BY MONTH(soh.OrderDate), p.Color
ORDER BY OrderMonth, p.Color;

-- Q6: Identify the five sales representatives who generated the highest total sales revenue in 2013, with quota and % exceeded. (Author: Obinna Ogbuagu)
-- A6: This query ranks sales reps by revenue, showing quota and percentage exceeded.
SELECT TOP 5 e.BusinessEntityID, p.FirstName + ' ' + p.LastName AS SalesRep,
       SUM(soh.TotalDue) AS TotalRevenue,
       sp.SalesQuota,
       (SUM(soh.TotalDue) - sp.SalesQuota) / sp.SalesQuota * 100 AS PercentExceeded
FROM Sales.SalesOrderHeader soh
JOIN Sales.SalesPerson sp ON soh.SalesPersonID = sp.BusinessEntityID
JOIN HumanResources.Employee e ON sp.BusinessEntityID = e.BusinessEntityID
JOIN Person.Person p ON e.BusinessEntityID = p.BusinessEntityID
WHERE YEAR(soh.OrderDate) = 2013
GROUP BY e.BusinessEntityID, p.FirstName, p.LastName, sp.SalesQuota
ORDER BY TotalRevenue DESC;

-- Q7: Can you list every base table in AdventureWorks and show its schema, table name, and table type? (Author: Courage Chiranga)
-- A7: This query uses INFORMATION_SCHEMA to list all base tables with schema and type.
SELECT TABLE_SCHEMA, TABLE_NAME, TABLE_TYPE
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_TYPE = 'BASE TABLE';

-- Q8: Which AdventureWorks tables contain a ProductID column, and what data type and nullability does each use? (Author: Courage Chiranga)
-- A8: This query finds all ProductID columns, showing schema, table, data type, and nullability.
SELECT TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE COLUMN_NAME = 'ProductID';
